(node:4536) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [192.168.0.118:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 192.168.0.118:27017]
    at Pool.<anonymous> (E:\Ram Working Folder\nvipani-master\micro\node_modules\mongodb-core\lib\topologies\server.js:505:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (E:\Ram Working Folder\nvipani-master\micro\node_modules\mongodb-core\lib\connection\pool.js:329:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (E:\Ram Working Folder\nvipani-master\micro\node_modules\mongodb-core\lib\connection\connection.js:245:50)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:4536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4536) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
